version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: npm test
      - run:
          name: Run tests with JUnit as reporter
          command: npm i jest -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: "JavaScript Linter"
          command: npm lint -- --format junit -o reports/junit/js-lint-results.xml

